spring:
  application:
    name: auth-service

server:
  port: 8090
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8090/eureka
